### ISSUE TITLE
ld.exe: cannot find -lavcodec: No such file or directory

### ISSUE THREAD

**Issue by hongfeiyucode** [voylin/yt_gozen_ffmpeg#1]
In file included from D:/mingw64/include/c++/14.2.0/bits/chrono.h:40,
                 from D:/mingw64/include/c++/14.2.0/mutex:43,
                 from godot-cpp\include/godot_cpp/core/class_db.hpp:48,
                 from godot-cpp\src\core\class_db.cpp:31:
D:/mingw64/include/c++/14.2.0/ctime:60:11: error: 'clock_t' has not been declared in '::'
   60 |   using ::clock_t;
      |           ^~~~~~~

**Comment by wardahub-design** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by hongfeiyucode** [comment]
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lavcodec: No such file or directory
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lavformat: No such file or directory
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lavfilter: No such file or directory
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lavdevice: No such file or directory
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lavutil: No such file or directory
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lswscale: No such file or directory
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lswresample: No such file or directory
collect2.exe: error: ld returned 1 exit status

=====
scons: *** [bin\libgozen.windows.template_debug.x86_64.dll] Error 1
scons: building terminated because of errors.

**Comment by hongfeiyucode** [comment]
> 也许这会有所帮助
> 
> https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ 我将必要的 dll 放在了存档中

Please describe the solution and where to modify it

**Comment by hongfeiyucode** [comment]
Both Windows and Linux have these issues, do you have any ideas？

**Comment by voylin** [comment]
> Both Windows and Linux have these issues, do you have any ideas？

I have no idea what distro you are on so not certain what's going wrong exactly, but I'm quite confident that you are just having linking error's. My recommendation would be to use https://github.com/VoylinsGamedevJourney/gde_gozen instead. That project is the full implementation and has an addon as well for easy implementation inside of your Godot project.

If you want to see this project as a learning experience, you could still move on to the GDE GoZen repo and look at the SConstruct file and copy some of the parts over as I normally have all linking errors fixed inside of there. I might revisit this project to update the linking error's in the future though, but not certain if I will be able to do it soon.

When you run into more issues, feel free to ask here, I'll keep this issue open till it works and till I fixed the linking errors in this Scons file ;)

**Comment by hongfeiyucode** [comment]
I am using Ubuntu, and I solved the first error by deleting time. h from the libavuti folder. Then I encountered the second error.
Could you please provide the compiled GDExtension? Thank you very much!

**Comment by voylin** [comment]
> I am using Ubuntu, and I solved the first error by deleting time. h from the libavuti folder. Then I encountered the second error. Could you please provide the compiled GDExtension? Thank you very much!

As I said, I'm not in a position that I have time to fix this repo, but https://github.com/VoylinsGamedevJourney/gde_gozen is the exact same, but with much better performance which does compile succesfully. There is a build script to make compiling for that one simple and if you want the compiled versions you can get them on these 2 links:
- https://ko-fi.com/s/c6ec85052b
- https://voylin.itch.io/gde-gozen-video-playback-addon-for-godot

**Comment by voylin** [comment]
Closing this as I saw from your other issues posted on other repo's that you have no intention on actually being helpful nor respect any of the maintainers time and effort. Have a good day.
